### ISSUE TITLE
not working in Chrome

### ISSUE THREAD

**Issue by shashisingh2010** [tomhallam/jQuery-Multicomplete#3]
Hi,

jQuery-Multicomplete is not working on chrome, but working on firefox. please update about this.

**Comment by tomhallam** [comment]
Hi there,

What error are you encountering?

If you're talking about the demo, I'm aware of it, seems GitHub don't serve
scripts from inside repos with the right mime type. If you download and
install as per instructions it should be fine.

Thanks
T

**Comment by shashisingh2010** [comment]
Hi Tom,

I have downloaded and installed locally. but I am facing the same issue.

Thanks,
Shashi

**Comment by tomhallam** [comment]
Thanks for your report - what error are you encountering exactly please?

**Comment by shashisingh2010** [comment]
the code <input type="text" name="multiselect" id="input-multicomplete" /> is not able to call below method in Google chrome.  e.g--- multicomplete method is not accessible through chrome.

```
  <script>
        $(document).ready(function() {
           $('#input-multicomplete').multicomplete({
               minimum_length: 1,
               result_template: function(result, group, matched_field) {
                    tmpl = '<div>';
                    if(!!result.image) {
                        tmpl += '<div class="image"><img src="' + result.image + '" /></div>';
                    }
                    tmpl += '<div>' + result.name + '</div>';
                    if(!!result.address) {
                        tmpl += '<div class="meta">' + result.address + '</div>';
                    }
                    // Only display this field if something was matched in it
                    if(!!result.cuisine && matched_field == 'cuisine') {
                        tmpl += '<div class="cuisine">Cuisine offered: ' + result.cuisine + '</div>';
                    }
                    tmpl += '</div>';
                    return tmpl;
               },
               result_click: function(row, group) {
                   alert('You chose "' + row.name + '" in ' + group);
               },
               source: 'demo-source.json'
           }); 
        });
    </script>
```

**Comment by tomhallam** [comment]
Can you show me the full HTML of your page - did you include `jquery.multicomplete.js` above that `<script>` tag?

**Comment by shashisingh2010** [comment]
yes... i have added

**Comment by shashisingh2010** [comment]
Please send ur email id...

i can't add files here...

**Comment by tomhallam** [comment]
I'd prefer not to share my email address, please use https://gist.github.com/ if you're having trouble including files.

**Comment by shashisingh2010** [comment]
I have added files and shared with u.

**Comment by shashisingh2010** [comment]
<script src="https://gist.github.com/shashisingh2010/5cf34176cd450faac769.js"></script>

**Comment by shashisingh2010** [comment]
shashisingh2010 / demo-source.json

**Comment by tomhallam** [comment]
I see absolutely no issues in your code (in fact it's just the demo!). I'm still not sure on what error you're receiving. Can you paste the **exact** error that your console is giving you?

**Comment by shashisingh2010** [comment]
is this code working on ur chrome?

**Comment by shashisingh2010** [comment]
XMLHttpRequest cannot load file:///C:/Users/Unikove/Downloads/tomhallam-jQuery-Multicomplete-c928407%281%29/tomhallam-jQuery-Multicomplete-c928407/example/demo-source.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.jquery.min.js:4 sendjquery.min.js:4 f.extend.ajaxjquery-multicomplete.js:201 multicomplete_searchajaxjquery-multicomplete.js:112 (anonymous function)

**Comment by shashisingh2010** [comment]
![image](https://cloud.githubusercontent.com/assets/11418738/6596108/116534a8-c817-11e4-8bdf-3316c107784a.png)

**Comment by tomhallam** [comment]
So the problem you have there is for the example to load the .json file, you will need to upload the files to a webserver. These requests won't work on local `file://` paths due to security restrictions imposed by the browser.

**Comment by shashisingh2010** [comment]
yes..thanks...

I have done the same.. now its working...

Thanks again
