### ISSUE TITLE
Dont work in newest chrome

### ISSUE THREAD

**Issue by Toliceek** [tomhallam/jQuery-Multicomplete#4]
Hi, I just tried your plugin. Looks nice, but working in newest chrome 46.0.2490.86 (64-bit)

Console error:
Refused to execute script from 'https://raw.github.com/tomhallam/jQuery-Multicomplete/master/lib/jquery-multicomplete.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

On local works fine, thanks.

**Comment by tomhallam** [comment]
This is because you can't include scripts directly from Github. As you found, using it locally will work fine.
